### ISSUE TITLE
Model injection in FormArray?

### ISSUE THREAD

**Issue by devanandb** [dtrelogan/react-formstate#5]
Hey there!

Thanks for all the support and help over the past few days, 

I am stuck with injecting model into FormArrays

**Comment by dtrelogan** [comment]
Can you share some code or give me something to go on? I believe either the
array example or the other input types example (or both) on the main page
show model injection.
On Jul 10, 2016 5:50 PM, "Devanand" <notifications@github.com> wrote:

Hey there!

Thanks for all the support and help over the past few days,

I am stuck with injecting model into FormArrays

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dtrelogan/react-formstate/issues/5>, or mute the thread
<https://github.com/notifications/unsubscribe/AQG5rmsUnbPzZ0R6LWh3rjlyp92QAEGXks5qUWkwgaJpZM4JI7Q7>
.
